name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/wzdnzd/aggregator.git
        
    - name: Fetch upstream
      run: |
        git fetch upstream
        
    - name: Sync fork
      run: |
        git checkout main
        git merge -X theirs upstream/main --allow-unrelated-histories || true
        git reset upstream/main -- .github/workflows/
        git checkout -- .github/workflows/
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Sync with upstream" || echo "Update upstream changes"
        
    - name: Push changes
      run: |
        git push origin main
